services:
    postgres:
        image: postgres:17
        container_name: phonebook-db
        restart: unless-stopped

        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        ports:
            - "5432:5432"

        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build: .
        container_name: phonebook-api
        restart: unless-stopped

        depends_on:
            - postgres

        ports:
            - "8080:8080"

        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/phonebook
            SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
            SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

            JWT_SECRET: ${JWT_SECRET}
            JWT_EXPIRATION: ${JWT_EXPIRATION}

volumes:
    postgres_data:
